CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_order_id TEXT NOT NULL,

    market_id BIGINT NOT NULL REFERENCES markets(id),
    user_id BIGINT NOT NULL REFERENCES users(id),

    side TEXT NOT NULL,
    kind TEXT NOT NULL,
    status TEXT NOT NULL,

    original_quantity_atomic NUMERIC(39, 0) NOT NULL,
    remaining_quantity_atomic NUMERIC(39, 0) NOT NULL,

    limit_price_atomic NUMERIC(39, 0),
    stop_price_atomic NUMERIC(39, 0),
    max_quote_amount_atomic NUMERIC(39, 0),

    sequence_number BIGINT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    triggered_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,

    CONSTRAINT orders_user_client_id_unique
        UNIQUE (user_id, client_order_id),

    CONSTRAINT orders_market_sequence_unique
        UNIQUE (market_id, sequence_number),
    
    CONSTRAINT orders_side_value
        CHECK (side IN ('BUY', 'SELL')),
    
    CONSTRAINT orders_kind_valid
        CHECK (kind IN ('LIMIT', 'MARKET', 'STOP_LIMIT')),

    CONSTRAINT orders_status_valid
        check (
            status IN (
                'PENDING_TRIGGER',
                'OPEN',
                'PARTIALLY_FILLED',
                'FILLED',
                'CANCELLED',
                'EXPIRED'
            )
        ),
    
    CONSTRAINT orders_original_quantity_positive
        CHECK (original_quantity_atomic > 0),
    
    CONSTRAINT order_remaining_quantity_valid
        CHECK (
            remaining_quantity_atomic >= 0
            AND remaining_quantity_atomic <= original_quantity_atomic
        ),

    CONSTRAINT orders_limit_price_positive
        CHECK (limit_price_atomic IS NULL OR limit_price_atomic > 0),

    CONSTRAINT orders_stop_price_positive
        CHECK (stop_price_atomic IS NULL OR stop_price_atomic > 0),

    CONSTRAINT orders_max_quote_positive
        CHECK (
            max_quote_amount_atomic IS NULL
            OR max_quote_amount_atomic > 0
        ),

    CONSTRAINT orders_sequence_positive
        CHECK (sequence_number IS NULL OR sequence_number > 0),

    CONSTRAINT orders_fields_match_kind
        CHECK (
            (
                kind = 'LIMIT'
                AND limit_price_atomic IS NOT NULL
                AND stop_price_atomic IS NULL
                AND max_quote_amount_atomic IS NULL
            )
            OR
            (
                kind = 'STOP_LIMIT'
                AND limit_price_atomic IS NOT NULL
                AND stop_price_atomic IS NOT NULL
                AND max_quote_amount_atomic IS NULL
            )
            OR
            (
                kind = 'MARKET'
                AND limit_price_atomic IS NULL
                AND stop_price_atomic IS NULL
                AND (
                    (side = 'BUY' AND max_quote_amount_atomic IS NOT NULL)
                    OR
                    (side = 'SELL' AND max_quote_amount_atomic IS NULL)
                )
            )
        ),

    CONSTRAINT orders_quantity_matches_status
        CHECK (
            (
                status IN ('PENDING_TRIGGER', 'OPEN')
                AND remaining_quantity_atomic = original_quantity_atomic
            )
            OR
            (
                status = 'PARTIALLY_FILLED'
                AND remaining_quantity_atomic > 0
                AND remaining_quantity_atomic < original_quantity_atomic
            )
            OR
            (
                status = 'FILLED'
                AND remaining_quantity_atomic = 0
            )
            OR
            (
                status IN ('CANCELLED', 'EXPIRED')
                AND remaining_quantity_atomic > 0
            )
        ),

    CONSTRAINT orders_kind_allows_status
        CHECK (
            (
                kind = 'LIMIT'
                AND status IN (
                    'OPEN',
                    'PARTIALLY_FILLED',
                    'FILLED',
                    'CANCELLED'
                )
            )
            OR
            (
                kind = 'MARKET'
                AND status IN ('FILLED', 'EXPIRED')
            )
            OR
            (
                kind = 'STOP_LIMIT'
                AND status IN (
                    'PENDING_TRIGGER',
                    'OPEN',
                    'PARTIALLY_FILLED',
                    'FILLED',
                    'CANCELLED'
                )
            )
        ),

    CONSTRAINT orders_closed_at_matches_status
        CHECK (
            (
                status IN ('FILLED', 'CANCELLED', 'EXPIRED')
                AND closed_at IS NOT NULL
            )
            OR
            (
                status IN ('PENDING_TRIGGER', 'OPEN', 'PARTIALLY_FILLED')
                AND closed_at IS NULL
            )
        )

);